# Generated by Django 2.2.6 on 2019-10-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('sex', models.CharField(max_length=6)),
                ('iso', models.CharField(max_length=6)),
            ],
        ),
    ]
